language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 8.1

matrix:
  fast_finish: true

before_install: composer self-update

install: composer update --prefer-dist --no-progress

script: if [ "$TRAVIS_PHP_VERSION" == "8.1" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi
